### ISSUE TITLE
WebContentsDelegate::CheckMediaAccessPermission: Not supported.

### ISSUE THREAD

**Issue by mariusbolik** [gokadzev/capacitor-music-controls-plugin-new#4]
Hello, the app crashes on my Samsung A52S when I call the Plugin. In Android Studio it says
```
WebContentsDelegate::CheckMediaAccessPermission: Not supported.
```
After adding `<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />` to AndroidManifest it says: 
```
E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:598)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalArgumentException: de.btcecho.app: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
        at com.gokadzev.capacitormusiccontrols.MusicControlsNotification.createBuilder(MusicControlsNotification.java:209)
        at com.gokadzev.capacitormusiccontrols.MusicControlsNotification.updateNotification(MusicControlsNotification.java:81)
        at com.gokadzev.capacitormusiccontrols.CapacitorMusicControls.updateMetadata(CapacitorMusicControls.java:224)
        at com.gokadzev.capacitormusiccontrols.CapacitorMusicControls.create(CapacitorMusicControls.java:42)
```

**Comment by gokadzev** [comment]
@mariusbolik Hello, could you try reinstall plugin with this command and tell me if it's fixed?

`npm install https://github.com/gokadzev/capacitor-music-controls-plugin-new.git#fix`

**Comment by mariusbolik** [comment]
Yes. It is fixed. Thank you for the excellent work and the fast response!!!
